import type { NewsItem } from "./types";

export const news: NewsItem[] = [
  {
    id: "demo-vietnam",
    title: "Chính sách mới được nhiều nguồn cùng cập nhật",
    slug: "chinh-sach-moi-duoc-nhieu-nguon-cap-nhat",
    summary: "Bản tin mẫu dùng để kiểm thử luồng tổng hợp nhiều nguồn trong môi trường phát triển.",
    keyPoints: ["Có nhiều nguồn đối chiếu", "Nội dung chỉ dùng trong môi trường phát triển"],
    category: "Việt Nam",
    primaryTopic: "Việt Nam",
    region: "Việt Nam",
    publishedAt: "10 phút trước",
    hotness: 82,
    reliability: 90,
    sources: ["Nguồn mẫu A", "Nguồn mẫu B"],
    imageTone: "green",
    topics: ["chính sách"],
  },
  {
    id: "demo-world",
    title: "Diễn biến quốc tế đáng chú ý trong ngày",
    slug: "dien-bien-quoc-te-dang-chu-y",
    summary: "Bản tin mẫu minh họa quy trình dịch, gộp và dẫn về nguồn quốc tế.",
    keyPoints: ["Có bản dịch tiếng Việt", "Giữ liên kết bài gốc"],
    category: "Thế giới",
    primaryTopic: "Thế giới",
    region: "Quốc tế",
    publishedAt: "25 phút trước",
    hotness: 78,
    reliability: 88,
    sources: ["International Demo"],
    originalLanguage: "en",
    translatedByAI: true,
    imageTone: "blue",
    topics: ["quốc tế"],
  },
  {
    id: "demo-economy",
    title: "Thị trường phản ứng trước thông tin kinh tế mới",
    slug: "thi-truong-phan-ung-thong-tin-kinh-te",
    summary: "Nội dung mẫu kiểm thử chuyên mục Kinh tế và bộ lọc nguồn.",
    keyPoints: ["Dữ liệu mẫu", "Không dùng trong production"],
    category: "Kinh tế",
    primaryTopic: "Kinh tế",
    region: "Việt Nam",
    publishedAt: "40 phút trước",
    hotness: 71,
    reliability: 86,
    sources: ["Nguồn mẫu Kinh tế"],
    imageTone: "gold",
  },
  {
    id: "demo-tech",
    title: "Công nghệ trí tuệ nhân tạo có thêm bước tiến mới",
    slug: "cong-nghe-tri-tue-nhan-tao-buoc-tien-moi",
    summary: "Bản tin mẫu kiểm thử tìm kiếm và phân loại chủ đề Công nghệ.",
    keyPoints: ["Thuộc chuyên mục Công nghệ", "Có thể tìm bằng từ khóa AI"],
    category: "Công nghệ",
    primaryTopic: "Công nghệ",
    region: "Quốc tế",
    publishedAt: "1 giờ trước",
    hotness: 69,
    reliability: 84,
    sources: ["Nguồn mẫu Công nghệ"],
    imageTone: "purple",
  },
  {
    id: "demo-health",
    title: "Khuyến cáo sức khỏe mới dành cho cộng đồng",
    slug: "khuyen-cao-suc-khoe-moi",
    summary: "Bản tin mẫu minh họa một nội dung có nguồn chính thức.",
    keyPoints: ["Khuyến cáo mẫu", "Luôn cần đọc nguồn gốc"],
    category: "Sức khỏe",
    primaryTopic: "Sức khỏe",
    region: "Việt Nam",
    publishedAt: "2 giờ trước",
    hotness: 64,
    reliability: 92,
    sources: ["Nguồn chính thức mẫu"],
    imageTone: "teal",
  },
];
