import { duplicateSimilarity, normalizeTitle } from "@/lib/ingestion/utils";
import type { AIProvider, ClassifiedArticle, ClusterArticleInput, ClusterSummary } from "./types";

function articleType(text: string) { if (/trở lại|hồi phục|return|fit again/.test(text)) return "recovery"; if (/chấn thương|injur/.test(text)) return "injury"; if (/chuyển nhượng|transfer|ký hợp đồng|signing/.test(text)) return "transfer"; if (/kết quả|đánh bại|thắng|thua|draw|win|beat|full.?time/.test(text)) return "result"; if (/đội hình|line.?up/.test(text)) return "lineup"; if (/trước trận|preview/.test(text)) return "preview"; if (/phát biểu|says|said|quote/.test(text)) return "quote"; return "news"; }
function sentences(value: string) { return value.replace(/\s+/g, " ").split(/(?<=[.!?])\s+/).map((item) => item.trim()).filter(Boolean); }
function words(value: string) { return value.trim().split(/\s+/).filter(Boolean).length; }

export class HeuristicAIProvider implements AIProvider {
  readonly name = "heuristic";
  async classifyArticle(input: { title: string; excerpt: string }): Promise<ClassifiedArticle> { const text = normalizeTitle(`${input.title} ${input.excerpt}`); const competitions = [["premier league", "Premier League"], ["champions league", "Champions League"], ["world cup", "World Cup"], ["v league", "V.League"]] as const; return { sport: "football", competition: competitions.find(([key]) => text.includes(key))?.[1] ?? null, teams: [], players: [], topics: [articleType(text)], articleType: articleType(text), language: /\b(the|and|with|from|after|before)\b/.test(text) ? "en" : "vi" }; }
  async summarizeCluster(input: { articles: ClusterArticleInput[] }): Promise<ClusterSummary> { const lead = input.articles[0]; const selected: string[] = []; for (const article of input.articles) for (const sentence of sentences(article.excerpt)) if (!selected.some((value) => duplicateSimilarity(value, sentence) > 0.8)) { selected.push(sentence); if (words(selected.join(" ")) >= 140) break; } const summary = selected.join(" ").split(/\s+/).slice(0, 180).join(" ") || lead?.excerpt || lead?.title || "Bản tin chưa được xử lý."; return { title: lead?.title ?? "Bản tin thể thao", summary, keyPoints: input.articles.slice(0, 5).map((article) => article.title), sourceIds: input.articles.map((article) => article.id) }; }
  async extractEntities() { return { teams: [], players: [], competitions: [] }; }
  async evaluateClusterMatch(input: { article: ClusterArticleInput; candidate: ClusterArticleInput[] }) { const score = Math.max(0, ...input.candidate.map((item) => duplicateSimilarity(input.article.title, item.title))); const left = articleType(normalizeTitle(`${input.article.title} ${input.article.excerpt}`)); const types = new Set(input.candidate.map((item) => articleType(normalizeTitle(`${item.title} ${item.excerpt}`)))); const compatible = types.has(left) || (left === "news" && types.has("news")); const confidence = compatible ? score : score * 0.35; return { sameEvent: confidence >= 0.55, confidence, reason: compatible ? "title_and_event_type" : "event_type_conflict" }; }
  async generateTimeline(input: { articles: ClusterArticleInput[] }) { return input.articles.filter((article) => article.publishedAt).map((article) => ({ occurredAt: article.publishedAt as string, content: `${article.sourceName ?? "Nguồn"} đăng: ${article.title}`, updateType: "source_update", supportingArticleIds: [article.id] })).sort((a, b) => Date.parse(a.occurredAt) - Date.parse(b.occurredAt)); }
  async identifyAgreements(input: { articles: ClusterArticleInput[] }) { return input.articles.length >= 2 ? [{ text: input.articles[0].title, sourceArticleIds: input.articles.map((article) => article.id) }] : []; }
  async identifyDisputes(input: { articles: ClusterArticleInput[] }) { const claims = input.articles.map((article) => ({ article, numbers: [...article.title.matchAll(/\b\d+(?:[.,]\d+)?\b/g)].map((match) => match[0]) })).filter((item) => item.numbers.length); const values = new Set(claims.flatMap((item) => item.numbers)); return claims.length >= 2 && values.size >= 2 ? [{ topic: "Các con số được nguồn nêu khác nhau", positions: claims.slice(0, 4).map((item) => ({ claim: item.article.title, sourceArticleIds: [item.article.id] })) }] : []; }
  async answerFromClusterContext(input: { question: string; articles: ClusterArticleInput[] }) { const terms = normalizeTitle(input.question).split(" ").filter((value) => value.length > 2); const evidence = input.articles.flatMap((article) => sentences(article.excerpt).map((text) => ({ id: article.id, text }))).filter((item) => terms.some((term) => normalizeTitle(item.text).includes(term))).slice(0, 3); return evidence.length ? `${evidence.map((item) => item.text).join(" ")} (Nguồn: ${[...new Set(evidence.map((item) => item.id))].join(", ")})` : "Không đủ dữ kiện trong các bài nguồn để trả lời câu hỏi này."; }
  async createMatchPreview() { return "Chưa đủ dữ liệu có kiểm chứng để tạo nhận định trước trận."; }
  async createMatchRecap() { return "Chưa đủ dữ liệu có kiểm chứng để tạo tóm tắt sau trận."; }
}
