import assert from "node:assert/strict";
import test from "node:test";
import { contentHash, duplicateSimilarity, isLikelyDuplicate, normalizeArticle, normalizeTitle } from "../../lib/ingestion/utils";
import { normalizePublishedDate } from "../../lib/ingestion/official-feed";

test("normalizes Vietnamese titles for comparison", () => { assert.equal(normalizeTitle("  Arsenal: Hoàn tất BUỔI tập! "), "arsenal hoan tat buoi tap"); });
test("article normalization trims content and hashes deterministically", () => { const input = { externalId:"1",url:"https://example.com/a",title:" Demo  title ",excerpt:" đoạn trích ",publishedAt:"2026-07-13T00:00:00Z" }; const article = normalizeArticle(input,"source-1"); assert.equal(article.title,"Demo title"); assert.equal(article.excerpt,"đoạn trích"); assert.equal(article.contentHash, contentHash(input)); });
test("duplicate heuristic combines keyword overlap and time", () => { assert.ok(duplicateSimilarity("Arsenal hoàn tất buổi tập chiến thuật", "Arsenal hoàn tất buổi tập trước trận") >= .55); assert.equal(isLikelyDuplicate({title:"Arsenal hoàn tất buổi tập chiến thuật",publishedAt:"2026-07-13T10:00:00Z"},{title:"Arsenal hoàn tất buổi tập trước trận",publishedAt:"2026-07-13T12:00:00Z"}),true); });
test("normalizes invalid, local and future feed timestamps", () => { const now = new Date("2026-07-13T16:00:00Z"); assert.equal(normalizePublishedDate("invalid", now), null); assert.equal(normalizePublishedDate(undefined, now), null); assert.equal(normalizePublishedDate("2026-07-13T19:00:00Z", now)?.toISOString(), now.toISOString()); assert.equal(normalizePublishedDate("Mon, 13 Jul 2026 11:48:02 EST", now)?.toISOString(), "2026-07-13T15:48:02.000Z"); assert.equal(normalizePublishedDate("Mon, 13 Jul 2026 16:06:00 BST", now)?.toISOString(), "2026-07-13T15:06:00.000Z"); assert.equal(normalizePublishedDate("7/13/2026 9:11:00 PM", now, true)?.toISOString(), "2026-07-13T14:11:00.000Z"); assert.equal(normalizePublishedDate("2026-07-13T11:45:00Z", now)?.toISOString(), "2026-07-13T11:45:00.000Z"); });
